### ISSUE TITLE
Use bigger font size for section descriptions

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystatstemplate#2]
![image](https://user-images.githubusercontent.com/11330453/185739527-ebc13cdd-a806-45fb-af13-1f4b4e533cb7.png)

**Comment by IndrajeetPatil** [comment]
I think this should do the trick:

```css
div[class="section level2"] > p.section-desc + p, /* reference index page */
div[class="section "] > p.section-desc + p /* articles index page */
{
    font-size: 1.3rem !important;
}
```
